---
- name: Test create file
  shell: echo 'This is a test for include task !!!'

- name: Test create file
  shell: echo 123 > test1.txt

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644
...
